backend:
  name: github
  repo: GWC-UNCC/Girls-Who-Code-at-UNCC
  #branch: main # Branch to update (optional; defaults to master)
  branch: feat/content-management-system # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }