backend:
  name: github
  repo: GWC-UNCC/Girls-Who-Code-at-UNCC
  #branch: main # Branch to update (optional; defaults to master)
  branch: feat/content-management-system # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
collections:
  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Event Date', name: 'date', widget: 'datetime' }
      - { label: 'Publish Date', name: 'publishdate', widget: 'datetime' }
      - { label: 'Event Flyer', name: 'image', widget: 'image', allow_multiple: false }
      - { label: 'Event Type', name: 'event_type', widget: 'select', options: ["Social", "Professional", "Web Dev", "Hackathon", "Workshop", "Game Night", "Technical"], multiple: false }
      - { label: 'Event Topic', name: 'event_topic', widget: 'list', allow_add: true, min: 1, max: 4 }
      - { label: 'Event Year', name: 'year', widegt: 'string' }
      - { label: 'Event Semester', name: 'semester', widget: 'select', options: ["Spring", "Summer", "Fall"], multiple: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }